In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import classification_report as cr
from sklearn.neighbors import KNeighborsClassifier

from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [2]:
data_location = "../TP3/smoking.csv"
data = pd.read_csv(data_location, sep = ",")

In [3]:
#veo el tamaño del data
data.shape

(55692, 27)

In [4]:
#data.head(10)

In [5]:
data["hearing(left)"].value_counts()

1.0    54267
2.0     1425
Name: hearing(left), dtype: int64

In [6]:
data["hearing(right)"].value_counts()

1.0    54236
2.0     1456
Name: hearing(right), dtype: int64

In [7]:
#Hay datos nulos?

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55692 entries, 0 to 55691
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   ID                   55692 non-null  int64  
 1   gender               55692 non-null  object 
 2   age                  55692 non-null  int64  
 3   height(cm)           55692 non-null  int64  
 4   weight(kg)           55692 non-null  int64  
 5   waist(cm)            55692 non-null  float64
 6   eyesight(left)       55692 non-null  float64
 7   eyesight(right)      55692 non-null  float64
 8   hearing(left)        55692 non-null  float64
 9   hearing(right)       55692 non-null  float64
 10  systolic             55692 non-null  float64
 11  relaxation           55692 non-null  float64
 12  fasting blood sugar  55692 non-null  float64
 13  Cholesterol          55692 non-null  float64
 14  triglyceride         55692 non-null  float64
 15  HDL                  55692 non-null 

https://www.kaggle.com/datasets/kukuroo3/body-signal-of-smoking

In [9]:
#vemos que valores puede tomar nuestra variable objetivo

In [10]:
data.smoking.unique()

array([0, 1], dtype=int64)

VAMOS A TRANSFORMAR LAS COLUMNAS HEARING(LEFT) Y HEARING(RIGTH) EN VARIABLES CATEGORICAS 

In [11]:
#df.Age = df.Age.replace({"0-17": 17, "+55": 60})

data["hearing(left)"] = data["hearing(left)"].replace({1: "normal", 2: "abnormal"})
data["hearing(right)"] = data["hearing(right)"].replace({1: "normal", 2: "abnormal"})

In [12]:
print(data["hearing(left)"].value_counts())
print(data["hearing(right)"].value_counts())

normal      54267
abnormal     1425
Name: hearing(left), dtype: int64
normal      54236
abnormal     1456
Name: hearing(right), dtype: int64


In [25]:
#registramos las columnas categoricas

In [13]:
categorical_columns = [col for col in data.columns if data[col].dtypes == 'object']
categorical_columns

['gender', 'hearing(left)', 'hearing(right)', 'oral', 'tartar']

In [14]:
#vemos que valores toma cada columna categorica

In [15]:
encoder_categories = []

X_categorical_columns = [x for x in categorical_columns]

for col in X_categorical_columns:    
    col_categories = data[col].unique()
    encoder_categories.append(col_categories)

encoder_categories

[array(['F', 'M'], dtype=object),
 array(['normal', 'abnormal'], dtype=object),
 array(['normal', 'abnormal'], dtype=object),
 array(['Y'], dtype=object),
 array(['Y', 'N'], dtype=object)]

#vemos que oral, tiene un solo tipo de valor, vamos a eliminarla de nuestro data ya que no aporta informacion extra

In [16]:
numerical_columns = [col for col in data.columns if data[col].dtypes != 'object']
numerical_columns

['ID',
 'age',
 'height(cm)',
 'weight(kg)',
 'waist(cm)',
 'eyesight(left)',
 'eyesight(right)',
 'systolic',
 'relaxation',
 'fasting blood sugar',
 'Cholesterol',
 'triglyceride',
 'HDL',
 'LDL',
 'hemoglobin',
 'Urine protein',
 'serum creatinine',
 'AST',
 'ALT',
 'Gtp',
 'dental caries',
 'smoking']

In [17]:
#vemos que valores toma cada columna numerica

In [18]:
encoder_numerical = []

X_numerical_columns = [x for x in numerical_columns if x != 'smoking']

for col in X_numerical_columns:    
    col_numerical = data[col].unique()
    encoder_numerical.append(col_numerical)

encoder_numerical

[array([    0,     1,     2, ..., 55683, 55684, 55691], dtype=int64),
 array([40, 55, 30, 45, 50, 35, 60, 25, 65, 20, 80, 75, 70, 85],
       dtype=int64),
 array([155, 160, 170, 165, 180, 150, 175, 140, 185, 145, 190, 135, 130],
       dtype=int64),
 array([ 60,  70,  75,  90,  65,  45,  55,  50,  85,  80, 100,  40,  95,
        105, 110, 120,  35, 115,  30, 125, 130, 135], dtype=int64),
 array([ 81.3,  81. ,  80. ,  88. ,  86. ,  85. ,  85.5,  96. ,  89. ,
         87. ,  59. , 108. ,  68. ,  68.2,  87.5,  79. ,  73. ,  82. ,
         75. ,  84.6,  91. ,  90. ,  95.4,  76. ,  95. ,  82.8,  92.5,
         65. ,  92. ,  78. ,  74. ,  69. ,  71. ,  81.5,  74.5,  77.9,
         85.1,  94.1,  73.7,  84.1,  72. ,  82.3,  76.3,  75.5,  77. ,
         63.3, 103.2,  70. ,  64. ,  83. ,  76.4,  84. ,  80.3, 102. ,
         82.4,  62. ,  61. , 100. ,  97.1,  74.6,  81.9,  79.5,  73.1,
         66. ,  93. ,  83.7,  76.5,  92.3,  94. ,  80.5,  63. ,  78.2,
         76.1,  90.5,  93.5,  77.7,  78.

In [19]:
#hay tres columnas que toman solo dos valores numericos. hay que covertirlos en dummies?

#RESUELTO, LO CONVERTIMOS EN DUMMIES

In [20]:
dummies_col = pd.get_dummies(data[["gender","tartar","hearing(left)","hearing(right)"]],drop_first=True)
dummies_col

gender_M  tartar_Y  hearing(left)_normal  hearing(right)_normal
0             0         1                     1                      1
1             0         1                     1                      1
2             1         0                     1                      1
3             1         1                     1                      1
4             0         0                     1                      1
...         ...       ...                   ...                    ...
55687         0         1                     1                      1
55688         0         1                     1                      1
55689         0         0                     1                      1
55690         1         0                     1                      1
55691         1         1                     1                      1

[55692 rows x 4 columns]

In [22]:
#concateno con el dataset

In [23]:
data = pd.concat([data, dummies_col], axis=1)

In [24]:
data.head()

ID gender  age  height(cm)  weight(kg)  waist(cm)  eyesight(left)  \
0   0      F   40         155          60       81.3             1.2   
1   1      F   40         160          60       81.0             0.8   
2   2      M   55         170          60       80.0             0.8   
3   3      M   40         165          70       88.0             1.5   
4   4      F   40         155          60       86.0             1.0   

   eyesight(right) hearing(left) hearing(right)  ...   ALT   Gtp  oral  \
0              1.0        normal         normal  ...  19.0  27.0     Y   
1              0.6        normal         normal  ...  19.0  18.0     Y   
2              0.8        normal         normal  ...  16.0  22.0     Y   
3              1.5        normal         normal  ...  26.0  18.0     Y   
4              1.0        normal         normal  ...  14.0  22.0     Y   

   dental caries  tartar  smoking  gender_M  tartar_Y  hearing(left)_normal  \
0              0       Y        0         0         1                     1   
1              0       Y        0         0         1                     1   
2              0       N        1         1         0                     1   
3              0       Y        0         1         1                     1   
4              0       N        0         0         0                     1   

   hearing(right)_normal  
0                      1  
1                      1  
2                      1  
3                      1  
4                      1  

[5 rows x 31 columns]

In [25]:
categorical_columns

['gender', 'hearing(left)', 'hearing(right)', 'oral', 'tartar']

In [26]:
# Construimos la matriz de features
X = data.drop(['gender', 'oral', 'tartar','smoking','hearing(left)', 'hearing(right)'], axis=1)
X.head()

y = data.smoking
y

0        0
1        0
2        1
3        0
4        0
        ..
55687    0
55688    0
55689    0
55690    0
55691    1
Name: smoking, Length: 55692, dtype: int64

In [27]:
# Separamos los conjuntos de entrenamiento y testeo, estratificando por clase
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y)

In [28]:
#estandarizamos el test y el train

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [29]:
#eleccion del mejor k

#for i in range(1, 100): 
 #   knn_d = KNeighborsClassifier(n_neighbors= i)
  #  knn_d.fit(X_train, y_train.values.ravel()) 
   # print(i, knn_d.score(X_test, y_test))

In [30]:
def scores_knn(X, y, start,stop, folds, metrica):
    
    # Usamos cross validation con 10 folds
    kf = KFold(n_splits=folds, shuffle=True, random_state=12)

    scores_para_df = []

    for i in range(start, stop):
    
        # En cada iteración, instanciamos el modelo con un hiperparámetro distinto
        model = KNeighborsClassifier(metric=metrica,n_neighbors=i)
    
        # cross_val_scores nos devuelve un array de 5 resultados,
        # uno por cada partición que hizo automáticamente CV
        cv_scores = cross_val_score(model, X_train, y_train, cv=kf)
    
        # Para cada valor de n_neighbours, creamos un diccionario con el valor
        # de n_neighbours y la media de los scores
        dict_row_score = {'score_medio':np.mean(cv_scores), 'n_neighbors':i}
    
        # Guardamos cada uno en la lista de diccionarios
        scores_para_df.append(dict_row_score)

    # Creamos el DataFrame a partir de la lista de diccionarios
    df_scores = pd.DataFrame(scores_para_df)
    
    # Retornamos el DF
    return df_scores 

# no recuerdo que era el folds, cual era el significado, VER
#creo tenia que ver con cross validation
#despues verificar que metodo es mejor,si euclidean manhattan o alguno de los que hay dando vueltas

In [31]:
df_scores = scores_knn(X_train, y_train, 1, 50, 10, 'euclidean')

KeyboardInterrupt: 

In [ ]:
# Asignamos el valor del k óptimo a una variable
best_k = df_scores.loc[df_scores.score_medio == df_scores.score_medio.max()]
best_k

In [42]:
# Elegimos el modelo óptimo que nos había indicado cross validation
model = KNeighborsClassifier(n_neighbors = best_k)

# Lo ajustamos sobre datos de entrenamiento
model.fit(X_train, y_train)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

In [ ]:
from sklearn.metrics import accuracy_score

# Evaluamos qué accuracy obtenemos en train
accuracy_score(y_train, model.predict(X_train))

In [ ]:
# Lo utilizamos para predecir en test
y_pred = model.predict(X_test)

In [ ]:
# Computamos el accuracy score en test
accuracy_score(y_test, y_pred)